-- DROWK CRM foundation schema
-- Forward-only once applied to a persistent environment.
-- IDs are generated by the application/runtime; no UUID extension is required.

CREATE TABLE tenants (
  id uuid PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  recorded_at timestamptz NOT NULL DEFAULT current_timestamp
);

CREATE TABLE accounts (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id),
  name text NOT NULL,
  status text NOT NULL DEFAULT 'ACTIVE',
  recorded_at timestamptz NOT NULL DEFAULT current_timestamp,
  supersedes_id uuid NULL,
  UNIQUE (tenant_id, id),
  FOREIGN KEY (tenant_id, supersedes_id) REFERENCES accounts(tenant_id, id)
);

CREATE TABLE contacts (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id),
  display_name text NOT NULL,
  recorded_at timestamptz NOT NULL DEFAULT current_timestamp,
  supersedes_id uuid NULL,
  UNIQUE (tenant_id, id),
  FOREIGN KEY (tenant_id, supersedes_id) REFERENCES contacts(tenant_id, id)
);

CREATE TABLE facilities (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id),
  account_id uuid NULL,
  name text NOT NULL,
  address_text text NULL,
  effective_at timestamptz NULL,
  recorded_at timestamptz NOT NULL DEFAULT current_timestamp,
  supersedes_id uuid NULL,
  UNIQUE (tenant_id, id),
  FOREIGN KEY (tenant_id, account_id) REFERENCES accounts(tenant_id, id),
  FOREIGN KEY (tenant_id, supersedes_id) REFERENCES facilities(tenant_id, id)
);

CREATE TABLE source_observations (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id),
  run_id uuid NOT NULL,
  correlation_id uuid NOT NULL,
  source_system text NOT NULL,
  source_native_id text NOT NULL,
  source_revision text NULL,
  observed_at timestamptz NULL,
  effective_at timestamptz NULL,
  retrieved_at timestamptz NOT NULL,
  ingested_at timestamptz NOT NULL,
  recorded_at timestamptz NOT NULL DEFAULT current_timestamp,
  source_watermark text NULL,
  adapter_version text NOT NULL,
  fingerprint text NOT NULL,
  raw_artifact_ref text NULL,
  source_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE (tenant_id, id)
);

CREATE UNIQUE INDEX source_observations_source_revision_uq
  ON source_observations (
    tenant_id,
    source_system,
    source_native_id,
    COALESCE(source_revision, '')
  );

CREATE TABLE connector_sync_state (
  tenant_id uuid NOT NULL REFERENCES tenants(id),
  connector_ref text NOT NULL,
  mailbox_ref text NOT NULL,
  committed_cursor text NULL,
  updated_at timestamptz NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (tenant_id, connector_ref, mailbox_ref)
);

CREATE TABLE connector_sync_checkpoints (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id),
  run_id uuid NOT NULL,
  correlation_id uuid NOT NULL,
  connector_ref text NOT NULL,
  mailbox_ref text NOT NULL,
  cursor_before text NULL,
  cursor_after text NULL,
  state text NOT NULL CHECK (state IN ('PREPARED','PASS','FAILED')),
  reason text NULL,
  source_count integer NULL CHECK (source_count IS NULL OR source_count >= 0),
  recorded_at timestamptz NOT NULL DEFAULT current_timestamp,
  completed_at timestamptz NULL,
  UNIQUE (tenant_id, id)
);

CREATE INDEX connector_sync_checkpoints_lookup_idx
  ON connector_sync_checkpoints (
    tenant_id,
    connector_ref,
    mailbox_ref,
    recorded_at DESC
  );

CREATE TABLE evidence (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id),
  run_id uuid NOT NULL,
  correlation_id uuid NOT NULL,
  observation_id uuid NOT NULL,
  subject_entity_type text NOT NULL,
  subject_entity_id uuid NULL,
  candidate_key text NULL,
  claim text NOT NULL,
  value_json jsonb NOT NULL,
  trust_state text NOT NULL CHECK (trust_state IN ('CLAIMED','VERIFIED','REJECTED')),
  observed_at timestamptz NULL,
  effective_at timestamptz NULL,
  retrieved_at timestamptz NULL,
  recorded_at timestamptz NOT NULL DEFAULT current_timestamp,
  expires_at timestamptz NULL,
  rights_class text NULL,
  supersedes_id uuid NULL,
  UNIQUE (tenant_id, id),
  FOREIGN KEY (tenant_id, observation_id) REFERENCES source_observations(tenant_id, id),
  FOREIGN KEY (tenant_id, supersedes_id) REFERENCES evidence(tenant_id, id)
);

CREATE TABLE identity_evidence (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id),
  evidence_id uuid NOT NULL,
  entity_type text NOT NULL,
  evidence_type text NOT NULL,
  raw_value text NOT NULL,
  normalized_value text NOT NULL,
  normalization_version text NOT NULL,
  trust_state text NOT NULL CHECK (trust_state IN ('CLAIMED','VERIFIED','REJECTED')),
  verification_method text NULL,
  verified_at timestamptz NULL,
  verified_by uuid NULL,
  recorded_at timestamptz NOT NULL DEFAULT current_timestamp,
  supersedes_id uuid NULL,
  UNIQUE (tenant_id, id),
  FOREIGN KEY (tenant_id, evidence_id) REFERENCES evidence(tenant_id, id),
  FOREIGN KEY (tenant_id, supersedes_id) REFERENCES identity_evidence(tenant_id, id)
);

CREATE TABLE entity_match_decisions (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id),
  run_id uuid NOT NULL,
  correlation_id uuid NOT NULL,
  subject_key text NOT NULL,
  resolution_scope text NOT NULL,
  status text NOT NULL CHECK (
    status IN (
      'MATCHED_SAFE',
      'NO_MATCH',
      'INSUFFICIENT_STRONG_EVIDENCE',
      'REVIEW_REQUIRED',
      'LINK_CONFLICT',
      'BLOCKED_PARENT_REQUIRED'
    )
  ),
  selected_entity_id uuid NULL,
  candidate_count integer NOT NULL CHECK (candidate_count >= 0),
  evidence_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  reason_codes jsonb NOT NULL DEFAULT '[]'::jsonb,
  fingerprint text NOT NULL,
  policy_version text NOT NULL,
  decided_by uuid NULL,
  recorded_at timestamptz NOT NULL DEFAULT current_timestamp,
  supersedes_id uuid NULL,
  CHECK (
    (status = 'MATCHED_SAFE' AND selected_entity_id IS NOT NULL)
    OR
    (status <> 'MATCHED_SAFE' AND selected_entity_id IS NULL)
  ),
  UNIQUE (tenant_id, id),
  FOREIGN KEY (tenant_id, supersedes_id) REFERENCES entity_match_decisions(tenant_id, id)
);

CREATE TABLE research_runs (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id),
  run_id uuid NOT NULL,
  correlation_id uuid NOT NULL,
  question text NOT NULL,
  question_contract jsonb NOT NULL,
  status text NOT NULL CHECK (
    status IN ('PLANNED','RUNNING','SUFFICIENT','EXHAUSTED','BLOCKED','FAILED')
  ),
  output_evidence_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  started_at timestamptz NULL,
  completed_at timestamptz NULL,
  recorded_at timestamptz NOT NULL DEFAULT current_timestamp,
  UNIQUE (tenant_id, id)
);

CREATE TABLE provider_runs (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id),
  run_id uuid NOT NULL,
  correlation_id uuid NOT NULL,
  capability text NOT NULL,
  provider text NOT NULL,
  operation text NOT NULL,
  interface text NOT NULL,
  access_class text NOT NULL CHECK (access_class IN ('READ','WRITE')),
  request_fingerprint text NOT NULL,
  response_fingerprint text NULL,
  result_state text NOT NULL CHECK (
    result_state IN (
      'PRESENT',
      'EMPTY_WITHIN_RESPONSE',
      'UNKNOWN',
      'ERROR',
      'PENDING',
      'PARTIAL'
    )
  ),
  estimated_cost_usd_micros bigint NULL,
  actual_cost_usd_micros bigint NULL,
  actual_cost_known boolean NOT NULL DEFAULT false,
  retrieved_at timestamptz NOT NULL,
  observed_at timestamptz NULL,
  rights_class text NULL,
  recorded_at timestamptz NOT NULL DEFAULT current_timestamp,
  UNIQUE (tenant_id, id)
);

CREATE TABLE policy_decisions (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id),
  run_id uuid NOT NULL,
  correlation_id uuid NOT NULL,
  subject_id uuid NULL,
  action text NOT NULL,
  disposition text NOT NULL CHECK (disposition IN ('ALLOW','DENY','REVIEW')),
  evidence_complete boolean NOT NULL,
  reason_codes jsonb NOT NULL DEFAULT '[]'::jsonb,
  policy_version text NOT NULL,
  recorded_at timestamptz NOT NULL DEFAULT current_timestamp,
  UNIQUE (tenant_id, id)
);

CREATE TABLE work_items (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id),
  run_id uuid NOT NULL,
  correlation_id uuid NOT NULL,
  work_key text NOT NULL,
  subject_id uuid NOT NULL,
  kind text NOT NULL,
  source_type text NOT NULL,
  source_refs jsonb NOT NULL DEFAULT '[]'::jsonb,
  source_version text NULL,
  next_action text NOT NULL,
  following_actions jsonb NOT NULL DEFAULT '[]'::jsonb,
  owner_ref text NULL,
  priority text NOT NULL CHECK (priority IN ('CRITICAL','HIGH','MEDIUM','LOW')),
  due_at timestamptz NULL,
  waiting_on text NOT NULL CHECK (
    waiting_on IN ('OWNER','CUSTOMER','THIRD_PARTY','DATE','NONE')
  ),
  work_state text NOT NULL CHECK (
    work_state IN (
      'NEEDS_ACTION','REVIEW','WAITING','SCHEDULED','BLOCKED',
      'NO_ACTION','DONE','CANCELLED','SUPERSEDED'
    )
  ),
  attention_class text NOT NULL CHECK (
    attention_class IN (
      'HARD_STOP_REVIEW','OVERDUE','DUE_TODAY','NEEDS_HUMAN_REVIEW',
      'READY_HIGH','READY_NORMAL','BLOCKED_NEEDS_OWNER','WAITING',
      'SCHEDULED','NO_ACTION'
    )
  ),
  reason_codes jsonb NOT NULL DEFAULT '[]'::jsonb,
  blocker text NULL,
  evidence_needed text NULL,
  autonomy_level text NOT NULL CHECK (
    autonomy_level IN (
      'A0_OBSERVE','A1_SUGGEST','A2_PREPARE',
      'A3_CONFIRMED_EXECUTE','A4_POLICY_AUTO','A5_NEVER_AUTO'
    )
  ),
  approval_required boolean NOT NULL,
  human_review_required boolean NOT NULL,
  policy_version text NOT NULL,
  source_watermark text NULL,
  supersedes_work_item_id uuid NULL,
  fingerprint text NOT NULL,
  available_at timestamptz NOT NULL,
  recorded_at timestamptz NOT NULL DEFAULT current_timestamp,
  UNIQUE (tenant_id, id),
  UNIQUE (tenant_id, work_key),
  FOREIGN KEY (tenant_id, supersedes_work_item_id) REFERENCES work_items(tenant_id, id)
);

CREATE TABLE approvals (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id),
  actor_id uuid NOT NULL,
  action text NOT NULL,
  target_ref text NOT NULL,
  payload_digest text NOT NULL,
  policy_version text NOT NULL,
  status text NOT NULL CHECK (
    status IN ('PENDING','APPROVED','REJECTED','EXPIRED','CONSUMED')
  ),
  expires_at timestamptz NOT NULL,
  recorded_at timestamptz NOT NULL DEFAULT current_timestamp,
  consumed_at timestamptz NULL,
  UNIQUE (tenant_id, id)
);

CREATE TABLE action_attempts (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id),
  run_id uuid NOT NULL,
  correlation_id uuid NOT NULL,
  action text NOT NULL,
  target_ref text NOT NULL,
  payload_digest text NOT NULL,
  approval_id uuid NULL,
  idempotency_digest text NOT NULL,
  state text NOT NULL CHECK (
    state IN ('PREPARED','DISPATCHING','ACCEPTED','FAILED','UNKNOWN','RECONCILED')
  ),
  provider_receipt_ref text NULL,
  error_category text NULL,
  attempted_at timestamptz NOT NULL,
  reconciled_at timestamptz NULL,
  recorded_at timestamptz NOT NULL DEFAULT current_timestamp,
  UNIQUE (tenant_id, id),
  UNIQUE (tenant_id, action, idempotency_digest),
  FOREIGN KEY (tenant_id, approval_id) REFERENCES approvals(tenant_id, id)
);

CREATE TABLE outcomes (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id),
  run_id uuid NOT NULL,
  correlation_id uuid NOT NULL,
  action_attempt_id uuid NULL,
  kind text NOT NULL,
  state text NOT NULL CHECK (state IN ('PROVISIONAL','CONFIRMED','RETRACTED')),
  observed_at timestamptz NOT NULL,
  recorded_at timestamptz NOT NULL DEFAULT current_timestamp,
  evidence_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  attribution_notes text NULL,
  UNIQUE (tenant_id, id),
  FOREIGN KEY (tenant_id, action_attempt_id) REFERENCES action_attempts(tenant_id, id)
);

CREATE TABLE idempotency_claims (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id),
  scope text NOT NULL,
  operation text NOT NULL,
  key_digest text NOT NULL,
  input_digest text NOT NULL,
  state text NOT NULL CHECK (state IN ('STARTED','COMPLETED','CONFLICT')),
  result_ref text NULL,
  recorded_at timestamptz NOT NULL DEFAULT current_timestamp,
  completed_at timestamptz NULL,
  UNIQUE (tenant_id, scope, operation, key_digest)
);

CREATE TABLE events (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id),
  event_type text NOT NULL,
  event_version integer NOT NULL CHECK (event_version > 0),
  occurred_at timestamptz NOT NULL,
  actor_id uuid NULL,
  run_id uuid NULL,
  correlation_id uuid NOT NULL,
  causation_id uuid NULL,
  subject_id uuid NULL,
  payload jsonb NOT NULL,
  recorded_at timestamptz NOT NULL DEFAULT current_timestamp,
  UNIQUE (tenant_id, id)
);

CREATE INDEX evidence_tenant_subject_idx
  ON evidence (tenant_id, subject_entity_type, subject_entity_id, recorded_at DESC);

CREATE INDEX observations_tenant_source_idx
  ON source_observations (tenant_id, source_system, retrieved_at DESC);

CREATE INDEX provider_runs_tenant_capability_idx
  ON provider_runs (tenant_id, capability, recorded_at DESC);

CREATE INDEX work_items_tenant_status_idx
  ON work_items (tenant_id, work_state, available_at);

CREATE INDEX action_attempts_tenant_state_idx
  ON action_attempts (tenant_id, state, attempted_at DESC);
