import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { test } from "node:test";
import { applyMigrations, PostgresIdentityRepository } from "../dist/index.js";
import { disposableDatabase } from "./disposable.mjs";

const pgTest = process.env.DROWK_TEST_DATABASE_URL ? test : test.skip;
pgTest("identity uses issuer+subject; duplicate and concurrent rebinding fail closed", async t => {
  const { pool } = await disposableDatabase(t);
  await applyMigrations(pool);
  const repository = new PostgresIdentityRepository(pool);
  const first = await repository.createUser("Synthetic");
  const second = await repository.createUser();
  assert.deepEqual(await repository.getUser(first.id), first);
  assert.notEqual(first.id, first.actorId);
  assert.equal(await repository.getUser(randomUUID()), null);
  const principal = { issuer: "synthetic", subject: "subject", email: "shared@example.invalid" };
  const identity = await repository.bindIdentity(first.id, principal);
  assert.equal(identity.userId, first.id);
  await assert.rejects(repository.bindIdentity(second.id, principal), { code: "23505" });
  assert.deepEqual(await repository.getIdentity(principal.issuer, principal.subject), identity);
  assert.equal(await repository.getIdentity("unknown", principal.subject), null);
  assert.equal(await repository.getIdentity(principal.issuer, principal.email), null);
  assert.equal((await repository.bindIdentity(second.id, { ...principal, issuer: "other" })).userId, second.id);
  await assert.rejects(repository.bindIdentity(first.id, { issuer: "", subject: "x" }), { code: "23514" });
  await assert.rejects(repository.bindIdentity(randomUUID(), { issuer: "synthetic", subject: "missing-user" }), { code: "23503" });
  const concurrent = { ...principal, subject: "concurrent" };
  const results = await Promise.allSettled([repository.bindIdentity(first.id, concurrent), repository.bindIdentity(second.id, concurrent)]);
  assert.equal(results.filter(result => result.status === "fulfilled").length, 1);
  assert.equal(results.find(result => result.status === "rejected").reason.code, "23505");
});

pgTest("membership scopes every operation, preserves revocation lineage and cannot silently reactivate", async t => {
  const { pool } = await disposableDatabase(t);
  await applyMigrations(pool);
  const repository = new PostgresIdentityRepository(pool);
  const user = await repository.createUser();
  const tenantA = randomUUID(), tenantB = randomUUID();
  await pool.query("INSERT INTO tenants (id, slug, name) VALUES ($1, 'synthetic-a', 'Synthetic A'), ($2, 'synthetic-b', 'Synthetic B')", [tenantA, tenantB]);
  const audit = { actorId: user.actorId, runId: randomUUID(), correlationId: randomUUID(), policyVersion: "synthetic-policy-v1" };
  const membership = await repository.createMembership(tenantA, user.id, audit);
  assert.equal(membership.status, "ACTIVE");
  assert.deepEqual(membership.createdAudit, audit);
  assert.deepEqual(await repository.getMembership(tenantA, user.id), membership);
  assert.equal(await repository.getMembership(tenantB, user.id), null);
  assert.equal(await repository.resolveActiveMembership(tenantB, user.id), null);
  assert.equal(await repository.revokeMembership(tenantB, user.id, audit), null);
  assert.deepEqual(await repository.resolveActiveMembership(tenantA, user.id), { tenantId: tenantA, userId: user.id, actorId: user.actorId });
  await assert.rejects(repository.createMembership(randomUUID(), user.id, audit), { code: "23503" });
  await assert.rejects(repository.createMembership(tenantB, randomUUID(), audit), { code: "23503" });
  const revokeAudit = { ...audit, runId: randomUUID(), correlationId: randomUUID() };
  const revoked = await repository.revokeMembership(tenantA, user.id, revokeAudit);
  assert.equal(revoked.status, "REVOKED");
  assert.ok(revoked.revokedAt);
  assert.deepEqual(revoked.createdAudit, audit);
  assert.deepEqual(revoked.revokedAudit, revokeAudit);
  assert.equal(await repository.resolveActiveMembership(tenantA, user.id), null);
  assert.deepEqual(await repository.revokeMembership(tenantA, user.id, audit), revoked);
  await assert.rejects(repository.createMembership(tenantA, user.id, audit), { code: "23505" });
});
